# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Roman
version:      1.07
version_from: lib/Math/Roman.pm
installdirs:  site
requires:
    Math::BigFloat:                1.44
    Math::BigInt:                  1.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
